---
site_name: Race Car Docs
site_url: https://github.com/pages/nino-kin/racecar-docs
site_description: Autonomous race car knowledge base
repo_name: https://github.com/nino-kin/racecar-docs
edit_uri: edit/main/docs

nav:
  - Home: index.md

theme:
  name: material
  language: "ja"
  icon:
    logo: material/school
    repo: fontawesome/brands/github
  favicon: assets/git.svg
  features:
    - tabs: true
    - header.autohide
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - content.action.edit
    # - toc.integrate

markdown_extensions:
  - adomition
  - attr_list
  - md_in_html
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - toc:
      permalink: true
  - codehilite:
      linennums: true
      guess_lang: false
      use_pygments: false
      noclasses: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji-genrator: !!python/name:material.extensions.emoji.to_svg
